</div>
  <!-- content starts -->
  <div id="content">
  
  
  <div id="about">
  <h1>Terms of Use</h1>
  
<p>
 
This document is an electronic record in terms of Information Technology Act, 2000 and rules there under  as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
 
<br />
<br />

Your use of the Website and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Website. If You transact on the Website, You shall be subject to the policies that are applicable to the Website for such transaction. By mere use of the Website, You shall be contracting with Company.com, these terms and conditions constitute Your binding obligations.  Hereafter, "Company" shall refer to LeaveAGift.
<br />
<br />

For the purpose of these Terms of Use, wherever the context so requires 'You' or "User" shall mean any natural or legal person who has agreed to become a member of the Website by providing Registration Data while registering on the Website as Registered User using the computer systems. Company allows User to surf the Website or making purchases without registering on the Website. The term "we", "us", "our" shall mean Company.
<br />
<br />
 
When You use any of the services provided by us through the Website, including but not limited to, (e.g., Customer Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time. It is Your responsibility to check these Terms of Use periodically for changes. Your continued use of the Website following the posting of changes will mean that You accept and agree to the changes. As long as You comply with these Terms of Use, We grants You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.
<br />
<br />


ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS IN THIS AGREEMENT, SO PLEASE READ THIS AGREEMENT CAREFULLY BEFORE PROCEEDING
<br />
<br />

<strong>Membership Eligibility</strong><br />

Use of the Company Website is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Company Website. If you are a minor i.e. under the age of 18 years, you shall not register as a member of the Company and shall not transact or use Company website. As a minor if you wish to use or transact on Company, such use or transaction may be made by your legal guardian or parents who have registered as users of the Company. Company reserves the right to terminate your membership and refuse to provide you with access to the Company if it is brought to Company's notice or if it is discovered that you are under the age of 18 years.
<br />
<br />

<strong>Your Account and Registration Obligations</strong><br />
 
If You use the Website, You shall be responsible for maintaining the confidentiality of your User ID and Password and You shall be responsible for all activities that occur under your User ID and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Website and refuse to provide You with access to the Website. 
<br />
<br />

<strong>Communications</strong><br />
 
When You use the  Website or send emails or other data, information or communication to us, You agree and understand that You are communicating with us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with You by email or by such other mode of communication, electronic or otherwise.
<br />
<br />

<strong>Charges</strong><br />
 
Membership on the Website is free. There is no charge or fee for browsing and buying products on the Website. However we reserve the right to charge fee and change its policies from time to time. In particular, we may at our sole discretion introduce new services and modify some or all of the existing services offered on the Website. In such an event t We reserves, without notice to You, the right to introduce fees for the new services offered or amend/introduce fees for existing services, as the case may be. Changes to the fee and related policies shall automatically become effective immediately once implemented on the Website. Unless otherwise stated, all fees shall be quoted in Indian Rupees. You shall be solely responsible for compliance of all applicable laws including those in India for making payments to us.
<br />
<br />

<strong>Use of the Website</strong><br />
 
 
You agree, undertake and confirm that your use of Website shall be strictly governed by the following binding principles:
<br />
<br />

1.	You shall not host, display, upload, modify, publish, transmit, update or share any information which:
(a) belongs to another person and to which You does not have any right to.
(b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to "indecent representation of women" within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;
(c) is misleading in any way. 
(d) is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, pedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual; 
(e) harasses or advocates harassment of another person;
(f) involves the transmission of "junk mail," "chain letters," or unsolicited mass mailing or "spamming"; 
(g) promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;
(h) infringes upon or violates any third party's rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity];
(i) promotes an illegal or unauthorized copy of another person's copyrighted work (see "Copyright complaint" below for instructions on how to lodge a complaint about uploaded copyrighted material), such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;
(j) contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);
(k) provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;
(l) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;
(n) contains video, photographs, or images of another person (with a minor or an adult).
(o) tries to gain unauthorized access or exceeds the scope of authorized access  to the Website or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Website or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;
(p) engages in commercial activities and/or sales without our prior written consent such as contests, sweepstakes, barter, advertising and pyramid schemes, or the buying or selling of "virtual" items related to the Website. Throughout this Terms of Use, Company's prior written consent" means a communication coming from Company's legal department, specifically in response to your request, and specifically addressing the activity or conduct for which you seek authorization;
(q) solicits gambling or engages in any gambling activity which We, in Our sole discretion, believes is or could be construed as being illegal;
(r) interferes with another user's use and enjoyment of the Website or any other individual's user and enjoyment of similar services;
(s) refers to any website or URL that, in Our sole discretion, contains material that is inappropriate for the Website or any other website, contains content that would be prohibited or violates the letter or spirit of these Terms of Use.
(t) harm minors in any way;
(u) infringes any patent, trademark, copyright or other proprietary rights or  third party's trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen items; 
(v) violates any law for the time being in force;
(w) deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;
(x) impersonate another person;
(y) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any Trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information; 
(z) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.
(aa) shall not be false, inaccurate or misleading; 
(ab) shall not, directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force. 
(ac) shall not create liability for us or cause us to lose (in whole or in part) the services of our ISPs or other suppliers; <br />
<br />

2.	You shall not use any "deep-link", "page-scrape", "robot", "spider" or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Website or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Website. We reserve our right to bar any such activity. 
<br />
<br />
3.	You shall not attempt to gain unauthorized access to any portion or feature of the Website, or any other systems or networks connected to the Website or to any server, computer, network, or to any of the services offered on or through the Website, by hacking, password "mining" or any other illegitimate means. 
<br />
<br />
4.	You shall not probe, scan or test the vulnerability of the Website or any network connected to the Website nor breach the security or authentication measures on the Website or any network connected to the Website. You may not reverse look-up, trace or seek to trace any information on any other user of or visitor to Website, or any other customer, including any account on the  Website not owned by You, to its source, or exploit the Website or any service or information made available or offered by or through the Website, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than your own information, as provided for by the Website. 
<br />
<br />
5.	You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about  us or the brand name or domain name used by us including the terms Company, LeaveGift.com, or otherwise engage in any conduct or action that might tarnish the image or reputation, of Company, or its suppliers or otherwise tarnish or dilute any Company's  trade or service marks, trade name and/or goodwill associated with such trade or service marks, trade name as may be owned or used by us including that duly licensed from Company. You agree that You will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Website or Company's systems or networks, or any systems or networks connected to Company. 
<br />
<br />
6.	You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Website or any transaction being conducted on the Website, or with any other person's use of the Website. 
<br />
<br />
7.	You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal You send to us on or through the Website or any service offered on or through the Website. You may not pretend that You are, or that You represent, someone else, or impersonate any other individual or entity. 
<br />
<br />
8.	You may not use the Website or any content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of Company and / or others. 
<br />
<br />
9.	Solely to enable us to use the information You supply us with, so that we are not violating any rights You might have in your Information, You agree to grant us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights You have in Your Information, in any media now known or not currently known, with respect to your Information. We will only use your information in accordance with the terms of use and Privacy Policy applicable to use of the Website. 
<br />
<br />
10.	From time to time, You shall be responsible for providing information relating to the items or services proposed to be sold by You. In this connection, You undertake that all such information shall be accurate in all respects. You shall not exaggerate or over emphasize the attributes of such items or services so as to mislead other Users in any manner. 
<br />
<br />
11.	You shall not engage in advertising to, or solicitation of, other users of the Website to buy or sell any products or services, including, but not limited to, products or services related to that being displayed on the Website or related to us. You may not transmit any chain letters or unsolicited commercial or junk email to other users via the Website. It shall be a violation of these Terms of Use to use any information obtained from the Website in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to another person other than us without our prior explicit consent. In order to protect our users from such advertising or solicitation, we reserve the right to restrict the number of messages or emails which a user may send to other users in any 24-hour period which we deems appropriate in its sole discretion. You understand that we have the right at all times to disclose any information (including the identity of the persons providing information or materials on the Website) as necessary to satisfy any law, regulation or valid governmental request. This may include, without limitation, disclosure of the information in connection with investigation of alleged illegal activity or solicitation of illegal activity or in response to a lawful court order or subpoena. In addition, we can (and You hereby expressly authorize us to) disclose any information about You to law enforcement or other government officials, as we, in our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury. 
<br />
<br />
12.	We reserve the right, but has no obligation, to monitor the materials posted on the Website. Company shall have the right to remove or edit any content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms of Use. Notwithstanding this right, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU POST ON THE WEBSITE AND IN YOUR PRIVATE MESSAGES. Please be advised that such Content posted does not necessarily reflect our or COMPANY views. In no event shall we or COMPANY assume or have any responsibility or liability for any Content posted or for any claims, damages or losses resulting from use of Content and/or appearance of Content on the Website. You hereby represent and warrant that You have all necessary rights in and to all Content which You provide and all information it contains and that such Content shall not infringe any proprietary or other rights of third parties or contain any libelous, tortious, or otherwise unlawful information. 
<br />
<br />
13.	Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the Website, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between You and such advertiser. We shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such advertisers on the Website. 
<br />
<br />
14.	It is possible that other users (including unauthorized users or "hackers") may post or transmit offensive or obscene materials on the Website and that You may be involuntarily exposed to such offensive and obscene materials. It also is possible for others to obtain personal information about You due to your use of the Website, and that the recipient may use such information to harass or injure You. We does not approve of such unauthorized uses, but by using the Website You acknowledge and agree that we are not responsible for the use of any personal information that You publicly disclose or share with others on the Website. Please carefully select the type of information that You publicly disclose or share with others on the Website. 
<br />
<br />
15.	We and COMPANY shall have all the rights to take necessary action and claim damages that may occur due to your involvement/participation in any way on your own or through group/s of People, intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services).
<br />
<br />
 

<strong>Contents Posted on Site</strong><br />

 
 
All text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music, artwork and computer code (collectively, "Content"), including but not limited to the design, structure, selection, coordination, expression, "look and feel" and arrangement of such Content, contained on the Website is owned and  controlled or licensed by us, and is protected by trade dress, copyright, patent and trademark laws, and various other intellectual property rights and unfair competition laws.
<br />
<br />
 


Except as expressly provided in these Terms of Use, no part of the Website and no Content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including "mirroring") to any other computer, server, website or other medium for publication or distribution or for any commercial enterprise, without our express prior written consent.
 
<br />
<br />


You may use information on the products and services purposely made available on the  Website for downloading, provided that You (1) do not remove any proprietary notice language in all copies of such documents, (2) use such information only for your personal, non-commercial informational purpose and do not copy or post such information on any networked computer or broadcast it in any media, (3) make no modifications to any such information, and (4) do not make any additional representations or warranties relating to such documents.
<br />
<br />
 


You shall be responsible for any notes, messages, e-mails, billboard postings, photos, drawings, profiles, opinions, ideas, images, videos, audio files or other materials or information posted or transmitted to the Website (collectively, " Content"). Such Content will become our property and You grant us the worldwide, perpetual and transferable rights in such Content. We shall be entitled to, consistent with our Privacy Policy as adopted in accordance with applicable law, use the Content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include the Content You provide. You agree that any Content You post may be used by us, consistent with our Privacy Policy and Rules of Conduct on Site as mentioned herein, and You are not entitled to any payment or other compensation for such use.
<br />
 

<br />
<strong> Other Businesses</strong><br />
 
Company does not take responsibility or liability for the actions, products, content and services on the Website, which are linked to Affiliates and / or third party websites using Website's APIs  or otherwise. In addition, Website may provide links to the third party websites of our affiliated companies and certain other businesses for which, We assume no responsibility for examining or evaluating the products and services offered by them. We do not warrant the offerings of, any of these businesses or individuals or the content of such third party website(s). Company does not endorse, in any way, any third party website(s) or content thereof.
<br />
<br />

<strong>Links</strong><br />
We welcome links to the Website. You may establish a hypertext link to the Website, provided that the link does not state or imply any sponsorship or endorsement of Your site by Company. You must not use on your site or in any other manner any trademarks, service marks or any other materials appearing on the Website, including any logos or characters, without our express written consent and the owner of the mark or materials. You must not frame or otherwise incorporate into another third party website or present in conjunction with or juxtaposed against such a website any of the content or other materials on the Website without our prior written consent.
<br />
<br />

<strong>Privacy</strong><br />
 
We view protection of Your privacy as a very important principle. We understand clearly that You and Your Personal Information is one of our most important assets. We store and process Your Information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), if any, on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act 2000 and Rules there under. Our current Privacy Policy is available at http://www.leaveagift.com/s/privacypolicy. If You object to Your Information being transferred or used in this way please do not use Website.
<br />
<br />

<strong>MANDATORY DECLARATION – COMPUTERS</strong><br />

1.	You hereby declare that You have provided all necessary Legal Details for the shipment of the product to the destination specified by You in the Order. 
<br />
2.	You further declare that the Product will be acquired for personal use of the Consignee and/or Buyer. The Product will not be sold, resold, bartered or in any way disposed for profit.
<br />
 
<br />

Disclaimer Of Warranties And Liability
<br />
 
 
This Website, all the materials and products (including but not limited to software) and services, included on or otherwise made available to You through this site are provided on "as is" and "as available" basis without any representation or warranties, express or implied except otherwise specified in writing. Without prejudice to the forgoing paragraph, we do not warrant that:
<br />

•	This Website will be constantly available, or available at all; or <br />

•	The information on this Website is complete, true, accurate or non-misleading. <br />

<br />

We will not be liable to You in any way or in relation to the Contents of, or use of, or otherwise in connection with, the Website.
<br />
<br />

 
We do not warrant that this site; information, Content, materials, product (including software) or services included on or otherwise made available to You through the Website; their servers; or electronic communication sent from us are free of viruses or other harmful components.

<br />
<br />
 
Nothing on Website constitutes, or is meant to constitute, advice of any kind.
<br />

<br />
 
All the Products sold on Website are governed by different state laws and if  we are unable to deliver such Products due to implications of different state laws, we will return or will give credit for the amount (if any) received in advance by us from the sale of such Product that could not be delivered to You.
<br />
<br />

You will be required to enter a valid phone number while placing an order on the Website. By registering Your phone number with us, You consent to be contacted by us via phone calls and / or SMS notifications, in case of any order or shipment or delivery related updates. We will not use your personal information to initiate any promotional phone calls or SMS.
<br />
<br />
 

<strong>Services</strong><br />
<br />

 
Payment
<br />
 
 
While availing any of the payment method/s available on the Website, we will not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You due to:
<br />

1.	Lack of authorization for any transaction/s, or 
2.	Exceeding the preset limit mutually agreed by You and between your "Bank/s", or 
3.	Any payment issues arising out of the transaction, or 
4.	Decline of transaction for any other reason/s. 
<br />
<br />

 
All payments made against the purchases/services on Website by you shall be compulsorily in Indian Rupees acceptable in the Republic of India. We do not accept any other form of currency with respect to the purchases made on Website.
<br />
<br />

Before shipping / delivering your order to you, we may request you to provide supporting documents (including but not limited to Govt. issued ID and address proof) to establish the ownership of the payment instrument used by you for your purchase. This is done in the interest of providing a safe online shopping environment to our users.
<br />
<br />
 

Payment<br />

While availing any of the payment method/s offered by us, we are not responsible or take no liability of whatsoever nature in respect of any loss or damage arising directly or indirectly to you out of the decline due to:
<br />
1. lack of authorization for any transaction/s, 
<br />
2. or exceeding the preset limit mutually agreed by you and between your "Bank/s", 
<br />
3. or any payment issues arising out of the transaction,
<br />
4. or decline of transaction for any other reason/s.
<br />
<br />
 
All payments made against the purchases/services on Company.com by you shall be compulsorily in Indian Rupees acceptable by the Union of India. Company.com does not accept any other form of currency with respect to the purchases.
<br />
<br />
 
Before shipping your order to you, we may request you to provide supporting documents (including but not limited to Govt. issued ID and address proof) to establish the ownership of the payment instrument used by you for your purchase. This is done in the interest of providing a safe online shopping environment to our users.
<br />
<br />

<strong>Wallet </strong><br />

 
The Wallet ("Wallet") is a pre-paid payment instrument which is associated with your Website account. You can maintain a balance of money with us and redeem it at your convenience.
We will not pay any interest on the amount maintained by you in your Wallet.
 <br />
<br />

Refill of Wallet: Your Wallet can be refilled, using any of the pre-paid payment options only. You will be able to recharge your Wallet up to an amount of INR 10,000 in one instance. There is no need to maintain a minimum balance.
<br />
<br />

Refund of Wallet Amount: Your Wallet comprises of three types of balances – Store credit (which is a credit granted by us typically in lieu of a cancelled order), Topped-up balance (which is a prepaid amount that You added to the Wallet to pay for future orders on the Website) and Promotional balance (which is credit granted by us purely for promotional or goodwill purposes). Topped-up balance (prepaid amount) as well as the Promotional balance added to the Wallet will be non-refundable while Store credit will continue to be entirely refundable.
<br />
<br />

 
Limitation of Liability: In no event will Company be liable for any special, incidental, indirect or consequential damages or losses of any kind, arising from the use of Wallet or association with the Wallet.
<br />
<br />
 

<strong>Digital Content: Music </strong><br />
 
 
<strong>Music (MP3 format):</strong> You will be able to purchase DRM-free digital music in MP3 file format on the Website. Such MP3 music files shall be provided to You as per your selection, subject to certain limitations as described herein. You shall be granted specified download rights of DRM-free MP3 music files from the catalog of MP3 music displayed on the Website. The MP3 music shall include full-length MP3 audio tracks at best available bit rate and certain other premium features, as may be provided on the Website from time to time. <br />
<br />
 
 
<strong>Territory: </strong>Currently You can purchase downloadable digital MP3 music only through the Website and Flyte Music Application as may be made available from time to time on the Website, only within the territory of India. <br />
<br />
 
<strong>Rights Granted: </strong>Upon Your payment of our fees for music, we grant You a non-exclusive, non-transferable right to use the downloaded MP3 music file for your personal, non-commercial, entertainment use, subject to and in accordance with the Terms of Use. You may copy, store, transfer and burn the MP3 music file only for your personal, non-commercial, entertainment use, subject to and in accordance with the Terms of Use. You represent, warrant and agree that You will use the MP3 music file only for your personal, non-commercial, entertainment use and not for any redistribution of the same or other use restricted in this Section. You agree not to infringe the rights of the copyright owners and to comply with all applicable laws in your use of the MP3 music file. You agree that You will not redistribute, transmit, assign, sell, broadcast, rent, share, lend, modify, adapt, edit, license or otherwise transfer or use MP3 music file. You are not granted any synchronization, public performance, promotional use, commercial sale, resale, reproduction or distribution rights for MP3 music file. You acknowledge that the MP3 music file embodies the intellectual property of a third party and is protected by law. <br />
<br />
 
<strong>Explicit Consent:</strong> You agree that we shall have no liability to You for MP3 music file downloaded by You on the Website if You find the same to be offensive, indecent or objectionable and expressions through the audio files are not subscribed by us. <br />
<br />
 
 
<strong>Payment:</strong> The Price List for each downloadable MP3 music file displayed on the Website represents the full retail price (inclusive of all taxes unless specified otherwise) for said downloadable MP3 music file. You shall pay for such downloadable MP3 music using one of the payment options available on the Website. The Price List mentions the prices of each downloadable MP3 music file and the User shall pay in Indian Currency (i.e. Indian Rupee). We reserve our right to change the prices of the MP3 music and services and the availability of the same at its sole discretion. <br />
<br />
 
Company will allow the user to buy MP3 music using the following forms of payments.
<br />
» Credit Cards
<br />
» Internet Banking;
<br />
» Debit Cards
<br />
» Wallet
<br />
» any other mode of payment, as may be decided and made available on the Website.
<br />
<br />

Please note that payment can be made only in India Rupees and all the above payment instruments must have been issued by entities operating in India and subject to Indian regulations.
<br />
<br />

Cash on Delivery as a mode of payment is not available for purchasing MP3 music on the Website currently.

<br />
<br />
 
Payment made by credit card or any other mode as mentioned above should be received by us on time. If for any reason we do not receive payment from the credit card issuer or any agent involved in any of the above payment modes, You agree that You shall pay all amounts due upon demand by us.
<br />
<br />

 
All Sales Final; Downloading and Risk of Loss; Availability of MP3 music files. All sales of MP3 music files are final. We do not accept returns of MP3 music files. Once You have purchased MP3 music files, we encourage You to download it promptly. If You are unable to complete a download, please contact customer service within 6 hours of the payment. Further we assumes no liability if your media player does not support the file format available on the Website or your browser does not support the music download application / software available on the Website, by whatever name called.

<br />
<br />
 
You bear all risk of loss after purchase and for any loss of MP3 music files You have downloaded, including any loss due to a computer or hard drive crash. We may, from time to time, at our sole discretion remove MP3 music files from the Service without notice.
<br />
<br />

 
Intellectual Property Rights: It is hereby specifically recorded that the copyright and other Intellectual Property in the music available on the Website is the sole and exclusive property of third parties. We are authorised by such third parties to upload the music on the Website for license of use to the end customers. Intellectual Property Rights for the purpose of this Agreement shall always mean and include copyrights whether registered or not, patents including rights of filing patents, trademarks, trade names, trade dresses, house marks, collective marks, associate marks and the right to register them, designs both industrial and layout, geographical indicators, moral rights, broadcasting rights, displaying rights, distribution rights, selling rights, abridged rights, translating rights, reproducing rights, performing rights, communicating rights, adapting rights, circulating rights, protected rights, joint rights, reciprocating rights, infringement rights. All those Intellectual Property rights arising as a result of domain names, internet or any other right available under applicable law shall vest in the domain of COMPANY as the owner of such domain name and in Company as authorised licensee. The Parties hereto agree and confirm that no part of any Intellectual Property rights mentioned hereinabove is transferred in the name of User and any intellectual property rights arising as a result of these presents shall also be in the absolute ownership, possession and our control or control of its licensors, as the case may be.

<br />
<br />
 
Your request to download a MP3 music file is personal to You, and the track may not be used, sold, rented, transferred, licensed or otherwise provided to any other user. The license to downloaded tracks includes only those rights explicitly stated herein (typically, the right to play back for your own personal use from your personal computer, CD player, digital player, or other personal consumer electronic device), and, for the avoidance of doubt, does not include the right to create a derivative work, to make copies other than for your own personal use, or to use the track in any commercial manner. You shall promptly notify us in writing upon your discovery of any unauthorized use or infringement.
<br />
<br />

 
<strong>Software:</strong> We may make available to You, from time to time, software for Your use in connection with the download of MP3 music files (any and all such software, individually and collectively, the "Software").
<br />
<br />

 
You may use the Software only in connection with the download of MP3 music files on the Website. You may not separate any individual component of the Software for use other than in connection to the download, may not incorporate any portion of it into Your own programs or compile any portion of it in combination with your own programs, may not transfer it for use with another service, or use it, or any portion of it, over a network and may not sell, rent, lease, lend, loan, distribute or sub-license the Software or otherwise assign any rights to the Software in whole or in part. We may discontinue some or all of any Software we provide, and we may terminate your right to use any Software at any time and in such event may modify it to make it inoperable.
<br />
<br />

 
Without limiting the Disclaimer of Warranties and Limitation of Liability in this terms of use, (i) in no event shall our or our software licensors' total liability to You for all damages arising out of or related to your use or inability to use the Software and / or download manager or any other application exceed the amount of INR 20; and (ii) in no event shall our or our Digital Content providers' total liability to You for all damages arising from your use of the Service, the Digital Content, or information, materials or products included on or otherwise made available to You through the Service (excluding the Software), exceed the amount You paid to purchase, on the Service, the Digital Content related to Your claim for damages.
<br />
<br />
 

<strong>Breach</strong><br />
 
 
Without limiting other remedies, we may limit Your activity, immediately remove Your information, warn other Users of Your actions, immediately temporarily/indefinitely suspend or terminate or block Your membership, and/or refuse to provide You with access to the Website in the event, but not limited to:
<br />

1.	If You breach the Terms of Use or Privacy Policy or other rules and  policies, if any; 
<br />
2.	If we are unable to verify or authenticate any information You provide; or 
If it is believed that Your actions may cause legal liability for You, other users or us. We may at any time at our sole discretion reinstate suspended users. A user that has been suspended or blocked may not register or attempt to register with us or use the Website in any manner whatsoever until such time that such user is reinstated by us. Notwithstanding the foregoing, if You breach the Terms of Use or Privacy Policy or other ruler and policies, we reserves the right to recover any amounts due and owing by You to us and to take strict legal action including but not limited to a referral to the appropriate police or other authorities for initiating criminal or other proceedings against You. 

<br />
<br />

 

<strong>Indemnity</strong><br />
 
You shall indemnify and hold harmless Company, its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys' fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights of a third party.

<br />
<br />


<strong>Applicable Law</strong><br />
 
This Agreement shall be governed by and interpreted and construed in accordance with the laws of India. The place of jurisdiction shall be exclusively in Bangalore.
<br />
<br />


 

<strong>Jurisdictional Issues/Sale in India Only</strong><br />
 
Unless otherwise specified, the material on the Website is presented solely for the purpose of sale in India. We make no representation that materials in the Website are appropriate or available for use in other locations/Countries other than India. Those who choose to access this site from other locations/Countries other than India do so on their own initiative and we are not responsible for supply of goods/refund for the goods ordered from other locations/Countries other than India, compliance with local laws, if and to the extent local laws are applicable.
<br />
<br />



<strong>Trademark, Copyright and Restriction</strong><br />
 
This site is controlled and operated by COMPANY and goods are sold by Company. All material on this site, including images, illustrations, audio clips, and video clips, are protected by copyrights, trademarks, and other intellectual property rights that are owned and controlled by us or by other parties that have licensed their material to us. Material on Website owned, operated, licensed or controlled by us is solely for Your personal, non-commercial use. You must not copy, reproduce, republish, upload, post, transmit or distribute such material in any way, including by e-mail or other electronic means and whether directly or indirectly and You must not assist any other person to do so. Without the prior written consent of the owner, modification of the materials, use of the materials on any other web site or networked computer environment or use of the materials for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks and other proprietary rights, and is prohibited. Any use for which You receive any remuneration, whether in money or otherwise, is a commercial use for the purposes of this clause.
<br />
<br />

<strong>Copyright complaint</strong><br />
 
We respect the intellectual property of others. In case You feel that Your work has been copied in a way that constitutes copyright infringement You can write to us at <a href="mailto:legal@leaveagift.com">legal@leaveagift.com</a>. <br />
<br />

<strong>Risk of loss</strong><br />
 
All items purchased on the Website are made pursuant to a shipment contract. This means that the risk of loss and title for such items pass to You upon our delivery to the carrier.
<br />
<br />

<strong>Product Description</strong><br />
 
We try to be as accurate as possible. However, we do not warrant that Product description or other content of this Website is accurate, complete, reliable, current, or error-free. If a product offered by us on the Website itself is not as described, Your sole remedy is to return it in unused condition.
<br />
<br />



<strong>Pricing/Typographical error</strong><br />
 
If Company comes across any difference in pricing resulting from typographic errors w.r.t pricing or product information, Company shall have the right to rectify the same or cancel the order(s) and refund monies, if any, collected from You within 10-15 business days of such corrective action taken. The mode of refund will be the same as at the time of placing the order. Cash on Delivery order refunds will be done by cheque.

<br />
<br />


<strong>30 Day Replacement Guarantee</strong><br />
 
We offer You REPLACEMENT WITHIN 30 DAYS FROM THE DATE OF DELIVERY ON THE product/s ordered on the Website i.e. if at the time of delivery and/or within 30 days from the date of delivery of the product/s, if any defect is found, then the buyer of the product/s can ask for replacement of the product/s subject to the following terms and conditions:
 
<br />


1    Notify us of any defects in the product/s at the time of delivery of the product/s and/or within 30 days from the date of delivery and the same product/s will be replaced in return of the defective product/s.
<br />
2    Replacement can be for the entire product/s or part/s of the product subject to availability of the same with us.
<br />
3    Replacement is offered for the product/s sold by us ONLY.
 
<br />
<br />


Following products shall not be eligible for return or replacement:
<br />
• Damages due to misuse of product;
<br />
• Incidental damage due to malfunctioning of product;
<br />
• Any consumable item which has been used/installed;
<br />
• Products with tampered or missing serial/UPC numbers;
<br />
• Digital products/services (Flyte music downloads).
<br />
• Any damage/defect which are not covered under the manufacturer's warranty
<br />
• Any product that is returned without all original packaging and accessories, including the box, manufacturer's packaging if any, and all other items originally included with the product/s delivered;
<br />
<br />

<strong>Disclaimer:</strong> "ANY DECISION ON 30 DAY REPLACEMENT GUARANTEE ON THE PRODUCT/S SOLD BY us is at our sole discretion and such decision shall be final and binding. We reserve the right to withdraw and/or alter from 30 DAY REPLACEMENT GUARANTEE at any time without giving any intimation of whatsoever nature."
<br />
<br />

<strong>Cancellation of order</strong><br />
 
We reserve the right to cancel any order at our sole discretion, under a situation where we are not able to meet the requirement of the order placed or order so placed/cancelled does not comply with the our policy or for any other reason. However, we will ensure that any communication of cancellation of an order, so cancelled, is intimated within appropriate time to the concerned person and any applicable refund will be made in reasonable time.
<br />
<br />

<strong>Limitation of Liability</strong><br />
 
IN NO EVENT SHALL COMPANY BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION WITH THIS AGREEMENT, EVEN IF COMPANY HAS BEEN INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES.
<br />
<br />

<strong>Our Contact </strong><br />
Please send any questions or comments (including all inquiries unrelated to copyright infringement) regarding this Website to <a href="mailto:support@leavagift.com">support@leavagift.com</a> <br />
<br />
 
 
<strong>Grievance officer</strong><br />
In accordance with Information Technology Act 2000 and rules made there under, the name and contact details of the Grievance Officer are provided below:
<a href="mailto:Grievance.officer@leaveagift.com">Grievance.officer@leaveagift.com</a> <br />
<br />



</p>
  
  
  </div>
  
  
  
  </div>
  <!-- content ends --> 
