<?php
$this->widget('zii.widgets.grid.CGridView',array(
                               'id'=>'parse-test',
                              //'template'=>'{pager}{summary}{items}',
                               'dataProvider'=>$dataProvider,
                               'columns'=>array(
                                 'id',
                                 'name',
                                 'age'
                                )
          ));